FROM node:8-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json .

RUN npm install
RUN npm install -g pm2
RUN npm install @elastic/elasticsearch
RUN npm install request

COPY . .

EXPOSE 3000
EXPOSE 9200
CMD [ "npm", "run", "start.dev" ]