version: '2.2'

services:
  app:
    image: node:10.15.3-alpine
    container_name: app-node
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "3000:3000"
    environment:
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - NODE_PORT=3000
     - ELASTIC_URL=http://elasticsearch:9200  
    links:
     - elasticsearch
    depends_on:
     - elasticsearch
    networks: 
     - esnet
  
  elasticsearch:
    container_name: app-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    logging:
      driver: none
    ports:
      - 9200:9200
      - 9300:9300

    networks: 
      - esnet

volumes:
  esdata:

networks:
  esnet: